name: walkwise
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  supabase: ^2.0.0
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.1
  provider: ^6.1.4
  flashy_tab_bar2: ^0.0.10
  flutter_svg: ^2.0.9

  google_maps_flutter: ^2.5.0

  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
  
  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 400
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 500

  
